// Configuration for Waveshare ESP32-S3 Touch LCD 7"
#ifndef ESP_PANEL_BOARD_CUSTOM_H
#define ESP_PANEL_BOARD_CUSTOM_H

// Board Information
#define ESP_PANEL_BOARD_NAME "WAVESHARE_ESP32_S3_TOUCH_LCD_7"

// LCD Configuration
#define ESP_PANEL_USE_LCD
#define ESP_PANEL_LCD_WIDTH              800
#define ESP_PANEL_LCD_HEIGHT             480

// LCD RGB Interface
#define ESP_PANEL_LCD_BUS_TYPE           ESP_PANEL_BUS_TYPE_RGB
#define ESP_PANEL_LCD_RGB_CLK_HZ         16000000
#define ESP_PANEL_LCD_RGB_TIMING_PCLK_HZ 16000000
#define ESP_PANEL_LCD_RGB_TIMING_H_RES   800
#define ESP_PANEL_LCD_RGB_TIMING_V_RES   480
#define ESP_PANEL_LCD_RGB_TIMING_HSYNC_PULSE_WIDTH 30
#define ESP_PANEL_LCD_RGB_TIMING_HSYNC_BACK_PORCH  16
#define ESP_PANEL_LCD_RGB_TIMING_HSYNC_FRONT_PORCH 210
#define ESP_PANEL_LCD_RGB_TIMING_VSYNC_PULSE_WIDTH 13
#define ESP_PANEL_LCD_RGB_TIMING_VSYNC_BACK_PORCH  10
#define ESP_PANEL_LCD_RGB_TIMING_VSYNC_FRONT_PORCH 22
#define ESP_PANEL_LCD_RGB_TIMING_FLAGS_HSYNC_IDLE_LOW  0
#define ESP_PANEL_LCD_RGB_TIMING_FLAGS_VSYNC_IDLE_LOW  0
#define ESP_PANEL_LCD_RGB_TIMING_FLAGS_DE_IDLE_HIGH    0
#define ESP_PANEL_LCD_RGB_TIMING_FLAGS_PCLK_ACTIVE_NEG 1
#define ESP_PANEL_LCD_RGB_TIMING_FLAGS_PCLK_IDLE_HIGH  0

// LCD RGB Data Pins
#define ESP_PANEL_LCD_RGB_DATA0_IO       15  // B0
#define ESP_PANEL_LCD_RGB_DATA1_IO       14  // B1
#define ESP_PANEL_LCD_RGB_DATA2_IO       13  // B2
#define ESP_PANEL_LCD_RGB_DATA3_IO       12  // B3
#define ESP_PANEL_LCD_RGB_DATA4_IO       11  // B4
#define ESP_PANEL_LCD_RGB_DATA5_IO       10  // G0
#define ESP_PANEL_LCD_RGB_DATA6_IO       9   // G1
#define ESP_PANEL_LCD_RGB_DATA7_IO       8   // G2
#define ESP_PANEL_LCD_RGB_DATA8_IO       7   // G3
#define ESP_PANEL_LCD_RGB_DATA9_IO       6   // G4
#define ESP_PANEL_LCD_RGB_DATA10_IO      5   // G5
#define ESP_PANEL_LCD_RGB_DATA11_IO      4   // R0
#define ESP_PANEL_LCD_RGB_DATA12_IO      3   // R1
#define ESP_PANEL_LCD_RGB_DATA13_IO      2   // R2
#define ESP_PANEL_LCD_RGB_DATA14_IO      1   // R3
#define ESP_PANEL_LCD_RGB_DATA15_IO      0   // R4

// LCD RGB Control Pins
#define ESP_PANEL_LCD_RGB_PCLK_IO        46
#define ESP_PANEL_LCD_RGB_VSYNC_IO       48
#define ESP_PANEL_LCD_RGB_HSYNC_IO       47
#define ESP_PANEL_LCD_RGB_DE_IO          45
#define ESP_PANEL_LCD_RGB_DISP_EN_IO     -1

// Backlight
#define ESP_PANEL_USE_BL                 1
#define ESP_PANEL_LCD_BL_IO              38
#define ESP_PANEL_LCD_BL_ON_LEVEL        1

// Touch Configuration
#define ESP_PANEL_USE_TOUCH               1
#define ESP_PANEL_TOUCH_BUS_TYPE         ESP_PANEL_BUS_TYPE_I2C
#define ESP_PANEL_TOUCH_TYPE              ESP_PANEL_TOUCH_TYPE_GT911
#define ESP_PANEL_TOUCH_I2C_ADDRESS       0x5D
#define ESP_PANEL_TOUCH_I2C_CLK_HZ        400000
#define ESP_PANEL_TOUCH_I2C_SCL_IO        20
#define ESP_PANEL_TOUCH_I2C_SDA_IO        19
#define ESP_PANEL_TOUCH_RST_IO           -1
#define ESP_PANEL_TOUCH_INT_IO           -1

// Touch calibration
#define ESP_PANEL_TOUCH_SWAP_XY           0
#define ESP_PANEL_TOUCH_MIRROR_X          0
#define ESP_PANEL_TOUCH_MIRROR_Y          0

// IO Expander
#define ESP_PANEL_USE_IO_EXPANDER         0

#endif // ESP_PANEL_BOARD_CUSTOM_H